[package]
name = "dumpster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.8"
axum = "0.6"
tower-http = "0.4"
libdumpster = { version = "*", path = "../libdumpster/" }
